package com.project.system.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.project.core.mybatis.model.BaseModel;
import com.project.core.security.model.FunModule;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.io.Serializable;
import java.util.List;
import java.util.Objects;

@Data
@EqualsAndHashCode(callSuper = false)
@JsonIgnoreProperties(value = {"handler"})
public class SysModule extends FunModule implements Serializable {

    private String targetDiv;
    private static final long serialVersionUID = 1L;

    private SysModule parentModule;

    @JsonBackReference
    public void setParentModule(SysModule parentModule) {
        this.parentModule = parentModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_module
     *
     * @mbg.generated Wed Mar 31 17:04:15 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", funcid=").append(this.funId);
        sb.append(", funcname=").append(funName);
        sb.append(", funtype=").append(funType);
        sb.append(", moddesc=").append(modDesc);
        sb.append(", isinuse=").append(isUse);
        sb.append(", supermodid=").append(this.getSuperModId());
        sb.append(", funicon=").append(funIcon);
        sb.append(", funorder=").append(funOrder);
        sb.append(", urllink=").append(urlLink);
        sb.append(", targetdiv=").append(targetDiv);
        sb.append(", system=").append(system);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SysModule)) return false;
        if (!super.equals(o)) return false;
        SysModule sysModule = (SysModule) o;
        return Objects.equals(getTargetDiv(), sysModule.getTargetDiv()) &&
                Objects.equals(getSystem(), sysModule.getSystem()) && super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), getTargetDiv(), getSystem());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_module
     *
     * @mbg.generated Wed Mar 31 17:04:15 CST 2021
     */
    @Override
    public Object getPrimaryKey() {
        return this.getFunId();
    }

}