package com.project.system.model;

import com.project.core.mybatis.model.BaseModel;

import java.io.Serializable;

public class SysDeptUser extends BaseModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept_user.ID
     *
     * @mbg.generated Thu May 06 15:40:20 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept_user.DeptID
     *
     * @mbg.generated Thu May 06 15:40:20 CST 2021
     */
    private String deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept_user.UserID
     *
     * @mbg.generated Thu May 06 15:40:20 CST 2021
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept_user.Updating_UID
     *
     * @mbg.generated Thu May 06 15:40:20 CST 2021
     */
    private String updatingUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept_user.Updating_Date
     *
     * @mbg.generated Thu May 06 15:40:20 CST 2021
     */
    private String updatingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dept_user
     *
     * @mbg.generated Thu May 06 15:40:20 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept_user.ID
     *
     * @return the value of sys_dept_user.ID
     * @mbg.generated Thu May 06 15:40:20 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept_user.ID
     *
     * @param id the value for sys_dept_user.ID
     * @mbg.generated Thu May 06 15:40:20 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept_user.DeptID
     *
     * @return the value of sys_dept_user.DeptID
     * @mbg.generated Thu May 06 15:40:20 CST 2021
     */
    public String getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept_user.DeptID
     *
     * @param deptid the value for sys_dept_user.DeptID
     * @mbg.generated Thu May 06 15:40:20 CST 2021
     */
    public void setDeptid(String deptid) {
        this.deptid = deptid == null ? null : deptid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept_user.UserID
     *
     * @return the value of sys_dept_user.UserID
     * @mbg.generated Thu May 06 15:40:20 CST 2021
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept_user.UserID
     *
     * @param userid the value for sys_dept_user.UserID
     * @mbg.generated Thu May 06 15:40:20 CST 2021
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept_user.Updating_UID
     *
     * @return the value of sys_dept_user.Updating_UID
     * @mbg.generated Thu May 06 15:40:20 CST 2021
     */
    public String getUpdatingUid() {
        return updatingUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept_user.Updating_UID
     *
     * @param updatingUid the value for sys_dept_user.Updating_UID
     * @mbg.generated Thu May 06 15:40:20 CST 2021
     */
    public void setUpdatingUid(String updatingUid) {
        this.updatingUid = updatingUid == null ? null : updatingUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept_user.Updating_Date
     *
     * @return the value of sys_dept_user.Updating_Date
     * @mbg.generated Thu May 06 15:40:20 CST 2021
     */
    public String getUpdatingDate() {
        return updatingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept_user.Updating_Date
     *
     * @param updatingDate the value for sys_dept_user.Updating_Date
     * @mbg.generated Thu May 06 15:40:20 CST 2021
     */
    public void setUpdatingDate(String updatingDate) {
        this.updatingDate = updatingDate == null ? null : updatingDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept_user
     *
     * @mbg.generated Thu May 06 15:40:20 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", deptid=").append(deptid);
        sb.append(", userid=").append(userid);
        sb.append(", updatingUid=").append(updatingUid);
        sb.append(", updatingDate=").append(updatingDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept_user
     *
     * @mbg.generated Thu May 06 15:40:20 CST 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysDeptUser other = (SysDeptUser) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getDeptid() == null ? other.getDeptid() == null : this.getDeptid().equals(other.getDeptid()))
                && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
                && (this.getUpdatingUid() == null ? other.getUpdatingUid() == null : this.getUpdatingUid().equals(other.getUpdatingUid()))
                && (this.getUpdatingDate() == null ? other.getUpdatingDate() == null : this.getUpdatingDate().equals(other.getUpdatingDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept_user
     *
     * @mbg.generated Thu May 06 15:40:20 CST 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDeptid() == null) ? 0 : getDeptid().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getUpdatingUid() == null) ? 0 : getUpdatingUid().hashCode());
        result = prime * result + ((getUpdatingDate() == null) ? 0 : getUpdatingDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept_user
     *
     * @mbg.generated Thu May 06 15:40:20 CST 2021
     */
    @Override
    public Object getPrimaryKey() {
        return this.getId();
    }
}