package com.project.system.model;

import com.project.core.mybatis.model.BaseModel;

import java.io.Serializable;

public class SysRoleFunc extends BaseModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_func.roleid
     *
     * @mbg.generated Fri Apr 02 15:27:23 CST 2021
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_func.funcid
     *
     * @mbg.generated Fri Apr 02 15:27:23 CST 2021
     */
    private String funcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_role_func
     *
     * @mbg.generated Fri Apr 02 15:27:23 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_func.roleid
     *
     * @return the value of sys_role_func.roleid
     * @mbg.generated Fri Apr 02 15:27:23 CST 2021
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_func.roleid
     *
     * @param roleid the value for sys_role_func.roleid
     * @mbg.generated Fri Apr 02 15:27:23 CST 2021
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_func.funcid
     *
     * @return the value of sys_role_func.funcid
     * @mbg.generated Fri Apr 02 15:27:23 CST 2021
     */
    public String getFuncid() {
        return funcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_func.funcid
     *
     * @param funcid the value for sys_role_func.funcid
     * @mbg.generated Fri Apr 02 15:27:23 CST 2021
     */
    public void setFuncid(String funcid) {
        this.funcid = funcid == null ? null : funcid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_func
     *
     * @mbg.generated Fri Apr 02 15:27:23 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleid=").append(roleid);
        sb.append(", funcid=").append(funcid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_func
     *
     * @mbg.generated Fri Apr 02 15:27:23 CST 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysRoleFunc other = (SysRoleFunc) that;
        return (this.getRoleid() == null ? other.getRoleid() == null : this.getRoleid().equals(other.getRoleid()))
                && (this.getFuncid() == null ? other.getFuncid() == null : this.getFuncid().equals(other.getFuncid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_func
     *
     * @mbg.generated Fri Apr 02 15:27:23 CST 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoleid() == null) ? 0 : getRoleid().hashCode());
        result = prime * result + ((getFuncid() == null) ? 0 : getFuncid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_func
     *
     * @mbg.generated Fri Apr 02 15:27:23 CST 2021
     */
    @Override
    public Object getPrimaryKey() {
        return this.getRoleid() + this.getFuncid();
    }
}